permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - $YOUR_ENV
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: eu-west-2
          role-to-assume: $ROLE_TO_ASSUME

      - name: Run build
        run: sam build

      - name: Deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env $YOUR_ENV
